ADC and DAC working
The ADC is sampling and the DAC outputs it
Error: Need to sync it up better so that the input and output matches better
Error: FIR gives very strange output
Missing: Plotting the Time and freq of Hm and time and freq of output buffer